### ISSUE TITLE
stop() method got exception

### ISSUE THREAD

**Issue by mrcancer91** [mapp-john/xftpd#3]
Hi,
While trying to run the code snippets on the Python console, I got below error
```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from xftpd import ftp_server
>>> FTP = ftp_server('/')
>>> FTP.start()
>>> print(FTP.Addr)
10.225.9.36
>>> print(FTP.User)
w8Re6Mw6Tt8Zn9B
>>> print(FTP.Pass )
u9Ub2Vx7Cl1Rl0K
>>> FTP.stop()
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    FTP.stop()
  File "C:\Python36\lib\site-packages\xftpd\__init__.py", line 147, in stop
    self.srv.kill()
AttributeError: 'Process' object has no attribute 'kill'
```

Please help to check! 
Best regards, 
Duy

**Comment by mrcancer91** [comment]
Update: After changing `self.srv.kill()` into `self.srv.terminate()`, the issue is resolved!
